---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs
subsets:
  - addresses:
      - ip: 10.0.0.1
    ports:
      - port: 1
---
apiVersion: v1
kind: Service
metadata:
  name: glusterfs
spec:
  ports:
  - port: 1
