apiVersion: apps/v1
kind: Deployment
metadata:
  name: heketi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: heketi
  template:
    metadata:
      labels:
        name: heketi
    spec:
      serviceAccountName: heketi
      containers:
      - image: heketi/heketi
        name: heketi
        env:
        - name: HEKETI_EXECUTOR
          value: kubernetes
        - name: HEKETI_FSTAB
          value: "/var/lib/heketi/fstab"
        - name: HEKETI_SNAPSHOT_LIMIT
          value: '14'
        - name: HEKETI_KUBE_GLUSTER_DAEMONSET
          value: "y"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: db
          mountPath: "/var/lib/heketi"
        - name: config
          mountPath: "/tmp"
        readinessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 3
          httpGet:
            path: "/hello"
            port: 8080
        livenessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 30
          httpGet:
            path: "/hello"
            port: 8080
      volumes:
      - name: db
        hostPath:
          path: "/heketi-data"
      - name: config
        configMap:
          name: heketi-config

---
apiVersion: v1
kind: Service
metadata:
  name: heketi
spec:
  selector:
    name: heketi
  ports:
  - name: heketi
    port: 8080
    targetPort: 8080
