apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
spec:
  selector:
    matchLabels:
      app: es
  serviceName: "es"
  replicas: 3
  template:
    metadata:
      labels:
        app: es
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - name: es
        image: yuiya/edu:elasticsearch-v7.10.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
          name: rest
        - containerPort: 9300
          name: inter
        env:
        - name: cluster.name
          value: rocc
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.initial_master_nodes
          value: "es-0, es-1, es-2"
        - name: discovery.zen.minimum_master_nodes
          value: "2"
        - name: discovery.seed_hosts
          value: "es-0.es, es-1.es, es-2.es"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        volumeMounts:
          - name: es-data
            mountPath: /usr/share/elasticsearch/data
        resources:
          requests:
            memory: "1000Mi"
          limits:
            memory: "2000Mi"
  volumeClaimTemplates:
    - metadata:
        name: es-data
        annotations:
          volume.beta.kubernetes.io/storage-class: nfs-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: es
spec:
  clusterIP: None
  ports:
    - name: rest
      port: 9200
      targetPort: 9200
    - name: inter
      port: 9300
      targetPort: 9300 
  selector: 
    app: es
